---

- name: LXD init
  block:
  - name: lxc info
    command: lxc info
    register: lxc_info_src0
    run_once: true
    changed_when: false

  - name: Debug | lxc info
    debug:
      var: lxc_info_src0
      verbosity: 1

  - name: create lxd-server.yml
    set_fact:
      master: "{{ lookup('template', 'lxd-server.yml.j2') }}"

  - name: Debug | lxd-server config
    debug:
      var: master
      verbosity: 1

  - name: Debug | lxd_cluster
    debug: var=lxd_cluster
  - name: Debug | inventory_hostname
    debug: var=inventory_hostname
  - name: Debug | groups.all[0]
    debug: var=groups.all[0]
  - name: Debug | lxc_info_src0
    debug: var=lxc_info_src0.stdout
  - name: Set temporary lxd-server configuration file
    copy:
      dest: /tmp/lxd-server.yml
      content: "{{ master }}"
      mode: '0644'

  - name: lxd init lxd-server.yml
    command: lxd init --preseed <
    args:
      stdin: "{{ master }}"
      creates: "{{ lxd_init_file_test }}"
    when: >
      lxc_info_src0.stdout.find('storage: \"\"') != -1
  - name: lxc info
    command: lxc info
    register: lxc_info_src
    run_once: true
    changed_when: false

  - name: store stdout from lxc info
    set_fact:
      lxc_info: "{{ lxc_info_src.stdout | from_yaml }}"